# Generated by Django 5.1.2 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of document', max_length=255)),
                ('description', models.TextField(help_text='Brief description for docuemnt contain', max_length=255)),
                ('file', models.FileField(help_text='Track and file', upload_to='files/%Y/%m/%d')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('uploaded_at', models.DateField(auto_now=True)),
                ('file_type', models.CharField(help_text='PDF, doc, exe, etc')),
            ],
        ),
    ]
