# Generated by Django 5.1.2 on 2024-11-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(help_text='User who uploaded the doc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(help_text='User who updated the doc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
