# Generated by Django 5.1.2 on 2024-11-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
