# Generated by Django 5.1.2 on 2024-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(help_text='PDF, doc, exe, etc'),
        ),
    ]
