# Generated by Django 5.1.2 on 2024-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_file_name_remove_document_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='doc', help_text='PDF, doc, exe, etc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Track and file', upload_to='files/%Y/%m/%d'),
        ),
    ]
