# Generated by Django 5.1.2 on 2024-11-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_name_document_type_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
